/*
 * This source file was generated by the Gradle 'init' task
 */
package org.srivette.gearingcalc.app;

import org.srivette.gearingcalc.records.DiffRatio;
import org.srivette.gearingcalc.records.GearRatio;
import org.srivette.gearingcalc.records.GearSpeedDataPoint;
import org.srivette.gearingcalc.records.TireSize;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Welcome to the gearing calculator!";
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
        List<GearSpeedDataPoint> results = app.getResults();
        app.displayResults(results);
    }

    public List<GearSpeedDataPoint> getResults() {
        DiffRatio diffRatio = new DiffRatio(3.45);
        TireSize tireSize = TireSize.fromSpecs(205, 70, 15);
        List<GearRatio> gearSet = Arrays.asList(
                new GearRatio(1, 2.87),
                new GearRatio(2, 1.89),
                new GearRatio(3, 1.28),
                new GearRatio(4, 1.0),
                new GearRatio(5, 0.81));

        List<Integer> rpmsOfInterest = Arrays.asList(500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 5500, 6000, 6500);

        List<GearSpeedDataPoint> results = new ArrayList<>();

        for (GearRatio gearRatio : gearSet) {
            for (Integer rpm : rpmsOfInterest) {
                GearSpeedDataPoint gearSpeedDataPoint = new GearSpeedDataPoint(gearRatio, diffRatio, tireSize, rpm);
                results.add(gearSpeedDataPoint);
            }
        }

        return results;
    }

    public void displayResults(List<GearSpeedDataPoint> gearSpeedDataPoints) {
        for (GearSpeedDataPoint gearSpeedDataPoint : gearSpeedDataPoints) {
            int gearNumber = gearSpeedDataPoint.gearRatio().gearNumber();
            int rpm = gearSpeedDataPoint.rpm();
            double speedMph = gearSpeedDataPoint.computeSpeedMph();
            String line = String.format("Gear %d \t\t RPM %d\t\t Speed(mph) %f", gearNumber, rpm, speedMph);
            System.out.println(line);
        }
    }
}
